### PR TITLE
Updated grammar definitions for typescript and tsx

### PR DESCRIPTION
**Pull request by DenisPostu**
Updated grammar definitions to fix unsupported multiple interface inheritance

Fixes issues #2 and #3

### CODE REVIEW

**Comment by tcarlsen** [comment]
why rename grammars/typescript-grammars-only.cson ??

And please remove the package version update (this will be updated bye the `amp publish` command

**Comment by DenisPostu** [comment]
@tcarlsen will fix later in the day and update PR, thanks for the feedback

**Comment by tcarlsen** [comment]
Im the one thanking

**Comment by tcarlsen** [comment]
ps. please use 2 space indent in the new tsx file

**Comment by tcarlsen** [comment]
Can I ask why?

**Pull request closed without merging**
